name = "gemini-cli-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

compatibility_flags = ["nodejs_compat"]

# --- KV Namespaces ---
kv_namespaces = [
  { binding = "GEMINI_CLI_KV", id = "9e8839a5d3a54322a70f845f0a851e2a" }
]

# [vars]


# --- Local Development Configuration ---
# This section configures local development with Docker and miniflare
[dev]
ip = "0.0.0.0"          # Bind to all interfaces for Docker access
port = 8787             # Port for local development server
# Note: --persist-to flag in Docker handles storage location

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
